# Generated by Django 3.2.6 on 2021-08-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(max_length=7)),
                ('story_points', models.IntegerField(blank=True, null=True)),
                ('sprint_name', models.CharField(max_length=120)),
                ('sprint_start_date', models.DateTimeField()),
                ('sprint_end_date', models.DateTimeField()),
                ('tags', models.CharField(blank=True, max_length=120, null=True)),
                ('scrum_team_name', models.CharField(blank=True, max_length=120, null=True)),
                ('severity', models.CharField(blank=True, max_length=120, null=True)),
                ('last_status_change_date', models.DateTimeField()),
                ('release_id', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=50)),
                ('value_area', models.CharField(blank=True, max_length=60, null=True)),
                ('effort', models.CharField(blank=True, max_length=10, null=True)),
                ('work_item_type', models.CharField(max_length=50)),
            ],
        ),
    ]
