# Generated by Django 3.2.6 on 2021-08-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpimodel',
            name='story_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
