# Generated by Django 3.2.6 on 2021-08-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piapp', '0002_alter_kpimodel_story_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpimodel',
            name='story_points',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
