# Generated by Django 3.2.6 on 2021-08-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piapp', '0003_alter_kpimodel_story_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpimodel',
            name='story_points',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
